language: generic

os:
- linux

sudo: required

addons:
  apt:
    package:
      - docker
      - git

after_success: |
  git clone https://github.com/anouarbensaad/docker-containerviewer
  cd docker-containerviewer
  chmod +x docker-viewer.sh
  ./docker-viewer.sh